### ISSUE TITLE
helm-select-action error

### ISSUE THREAD

**Issue by Pitometsu** [ShingoFukuyama/helm-swoop#59] opened 2015-03-30 21:51 UTC
```elisp
Sole action: (lambda ($line) (helm-swoop--goto-line (when (string-match ^[0-9]+ $line) (string-to-number (match-string 0 $line)))) (let (($regex (mapconcat (quote identity) (split-string helm-pattern  ) \|))) (when (or (and (and (featurep (quote migemo)) (featurep (quote helm-migemo))) (migemo-forward $regex nil t)) (re-search-forward $regex nil t)) (goto-char (match-beginning 0)))) (helm-swoop--recenter))
```

**Comment by ShingoFukuyama** [comment] 2015-04-07 10:56
How can I reproduce the error?

**Comment by yamada-github-account** [comment] 2015-08-30 16:32
I met the same error.
Maybe the problem is not select action itself, but persistent action.

The procesure is following;
1. M-x helm-swoop RET
2.Type some words
3. Press C-z (or TAB)
Then mini-buffer shows,
> Sole action: (lambda ($line) (helm-swoop--goto-line (when (string-match ^[0-9]+ $line) (string-to-number (match-string 0 $line)))) (let (($regex (mapconcat (quote identity) (split-string helm-pattern  ) \|))) (when (or (and (and (featurep (quote migemo)) (featurep (quote helm-migemo))) (migemo-forward $regex nil t)) (re-search-forward $regex nil t)) (goto-char (match-beginning 0)))) (helm-swoop--recenter))

When I do in helm-multi-swoop, mini-buffer shows
> Sole action: #[257 \302\300!\210\303\304^B"\205^Q^@\305\306\307^C"!eb\210\211Sy\266^B\310\311\312\313   \314"\315#\316\317#\203,^@\307\224b\210\320\321 \322\245!\207 [.emacs helm-pattern switch-to-buffer string-match ^[0-9]+ string-to-number match-string 0 re-search-forward mapconcat identity split-string   \| nil t recenter window-height 2] 7
>
>(fn $LINE)]

I assumed helm-swoop would show the list of actions like helm-find-file.
In both case, helm-swoop--goto-line itself can work by pressing RET.

My environment is following:
OS X Yosemite 10.10.5
GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0) of 2015-08-20
helm               20150824.2209
helm-swoop   20150704.839

**Comment by syohex** [comment] 2015-09-01 05:53
This is not error however this is not good. I have sent PR(#78) and it has been merged. Please check latest version.

![output](https://cloud.githubusercontent.com/assets/554281/9597122/3c91a7c6-50b9-11e5-96f8-69b69d87fdca.gif)

**Comment by yamada-github-account** [comment] 2015-09-02 23:02
Thank you very much!

**Closed** 2015-09-07 13:23 UTC
